#version: "3.9"
services:
  godns:
    build:
      context: .
      dockerfile: Dockerfile
    image: godns
    container_name: godns
    ports:
      - "53:53/udp"
    volumes:
      - ./config/godns.yaml:/etc/godns.yaml:ro
      - /var/log/godns:/var/log/godns
      - /etc/godns:/etc/godns
      - ad-data:/var/lib/godns
    cap_add:
      - NET_BIND_SERVICE
    restart: unless-stopped
    environment:
      TZ: "Europe/Minsk"
    dns:
      - 1.1.1.1
      - 8.8.8.8
volumes:
  ad-data:
    driver: local
