#version: "3.9"
services:
  godns:
    build:
      context: .
      dockerfile: Dockerfile
    image: godns
    container_name: godns
    ports:
      - "53:53/udp"
    volumes:
      - ./config/godns.yaml:/etc/godns.yaml:ro
      - /var/log/godns:/var/log/godns
    cap_add:
      - NET_BIND_SERVICE
#      - NET_ADMIN
    restart: unless-stopped
    environment:
      TZ: "Europe/Minsk"
