listen:       ":53"
up1:          "https://cloudflare-dns.com/dns-query"
up2:          "https://dns.google/dns-query"
up3:          "https://dns.quad9.net/dns-query"
cache_size:   10000     # записей
timeout:      2s
log_level:    debug
vrrp:
  enable:     no
  iface:      enp3s0
  vrid:       10
  vip:        192.168.1.9
  prior:      255
  adver_int:  1
adblock:
  enable:     yes
  update:     24h
  time:       03:00:00
  black:
    - https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/domains/pro.plus.txt
    - https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
    - https://phishing.army/download/phishing_army_blocklist.txt
  white:
    - metrics.icloud.com
    - safebrowsing.googleapis.com
