listen:       ":53"
up1:          "https://cloudflare-dns.com/dns-query"
up2:          "https://dns.google/dns-query"
up3:          "https://dns.quad9.net/dns-query"
cache_size:   10000     # записей
timeout:      2s
log_level:    debug
